apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  labels:
    app: mysql
    tier: db
    project: expense
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: mysql
      tier: db
      project: expense
  template:
    metadata:
      labels:
        app: mysql
        tier: db
        project: expense
    spec:
      containers:
        - name: mysql
          image: kdprasad028/mysql:{{ .Values.deployment.imageVersion }}
          # image: joindevops/mysql:v1
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
    tier: db
    project: expense
  ports:
    - name: mysql-port
      protocol: TCP
      port: 3306 
      targetPort: 3306
    